[build]
  command = "yarn build" 
  functions = "built-lambda"
  publish = "build"
[functions]
  directory = "functions"
[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200