[build]
    functions = "functions"
    command = "npm run build"
    targetPort = "3000"
[functions]
  directory = "my_functions"
[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200